### ISSUE TITLE
Make fails on Arch 

### ISSUE THREAD

**Issue by ctnlaring** [papyros/papyros-shell#228] opened 2016-02-04 21:34 UTC
/home/collin/Papyros/papyros-shell/decorations/main.cpp:316: Parse error at "IID"
AUTOGEN: error: process for /home/collin/Papyros/papyros-shell/build/decorations/main.moc failed:
/home/collin/Papyros/papyros-shell/decorations/main.cpp:316: Parse error at "IID"

moc failed...
decorations/CMakeFiles/material_automoc.dir/build.make:57: recipe for target 'decorations/CMakeFiles/material_automoc' failed
make[2]: **\* [decorations/CMakeFiles/material_automoc] Error 1
CMakeFiles/Makefile2:279: recipe for target 'decorations/CMakeFiles/material_automoc.dir/all' failed
make[1]: **\* [decorations/CMakeFiles/material_automoc.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by ricardomv** [comment] 2016-02-04 23:43
Please check if issues were already submitted before creating a new one this is a duplicate of #203 and other information other than the build log would be nice as the versions of the libraries and the failing commit were the issue was tested.

**Closed as completed by ricardomv** 2016-02-04 23:43 UTC
Labels: duplicate
