### ISSUE TITLE
Type Panel unavailable

### ISSUE THREAD

**Issue by fedya** [papyros/papyros-shell#58] opened 2015-03-26 00:22 UTC
I'm trying to run papyros-shell on my imx6q board

[root@localhost qml-compositor]# /usr/bin/papyros-shell -platform eglfs        
MESA-LOADER: malformed or no PCI ID
gbm: failed to open any driver (search paths /usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/imx-drm_dri.so: cannot open shared object file: No such file or directory
failed to load driver: imx-drm
No modes available for output "HDMI1"
QtCompositor: Failed to initialize EGL display. There is no EGL_WL_bind_wayland_display extension.
load glyph failed err=24 face=0x1540658, glyph=54
load glyph failed err=24 face=0x1540658, glyph=74
load glyph failed err=24 face=0x1540658, glyph=71
Failed to move cursor: -14
qrc:/qml/Shell.qml:150:5: Type Panel unavailable
qrc:/qml/panel/Panel.qml:146:9: Type AppDrawer unavailable
qrc:/qml/launcher/AppDrawer.qml:111:9: Cannot assign to non-existent property "iconSize"
load glyph failed err=24 face=0xad80fbd8, glyph=92
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.

**Comment by fedya** [comment] 2015-03-26 00:22
And i see only red screen

**Comment by juston-li** [comment] 2015-03-26 00:27
qrc:/qml/launcher/AppDrawer.qml:111:9: Cannot assign to non-existent property "iconSize"

I got it to work commenting out iconSize: units.dp(50)

**Comment by juston-li** [comment] 2015-03-26 00:48
iconSize was removed by this commit from qml-desktop 
https://github.com/papyros/qml-desktop/commit/81e8f4d23a21fd5cad93a4c4e5b6a3b381036878

**Comment by fedya** [comment] 2015-03-26 11:52
When i removed it, just got another errors
https://gist.github.com/fedya/ec83243eba8765312212

**Comment by hsarkanen** [comment] 2015-04-01 13:09
I have also tried papyros-shell on imx6 board earlier this year, with no luck. IIRC I saw also some blue error screen which came after the red one mentioning having some runtime qml issues around papyros-shell and its dependencies similar to your "iconSize error", which I think were also caused by that I didn't have working combination of the papyros repositories. Things like greenisland integration: https://github.com/papyros/papyros-shell/issues/53#issuecomment-77694018 on papyros are changing so fast, that I decided to give up for a while.

Seems like your problems are imx-drm related. Which kernel version you tried? I tried only Freescale Yocto supported and patched kernel 3.10.53_1.1.0_ga: https://github.com/Freescale/meta-fsl-arm-extra/blob/master/recipes-kernel/linux/linux-wandboard_3.10.53.bb. In the mainline there have been lot of [changes](http://www.phoronix.com/scan.php?page=news_item&px=MTgyNzg) around the [drivers](https://github.com/torvalds/linux/tree/master/drivers/gpu/drm/imx) lately, so it might be interesting to try 3.19 also.

Also Qt version might affect. Which version you tried? I used "5.4.1+git%" version from Yocto: https://github.com/meta-qt5/meta-qt5/blob/master/conf/distro/include/qt5-versions.inc which means qtbase https://github.com/qtproject/qtbase/commit/a782369071db1d89448c0b94248d31fa877bcf8c and qtwayland https://github.com/qtproject/qtwayland/commit/1e32e71403a6a9cb117343464fbc34564598e831. I also tried using a small patch: https://gist.github.com/hsarkanen/7f32cee244bde8057b95. With this Qt version I managed to get QtCompositor example: https://github.com/qtproject/qtwayland/tree/dev/examples/wayland/qwindow-compositor running.

**Comment by fedya** [comment] 2015-04-01 14:01
>Which kernel version you tried?
3.10.53 - "blue screen" not working without proprietary video drivers
3.19.2 -  at least i can run papyros with free stuff

>Also Qt version might affect.
5.5.0.aplha

if you want i can provide you a small instruction how to run OpenMandriva ARMv7 image on imx6 device
All packages related to papyros-shell and qt5.5.0 already built for armv7hl (hardfloat)

take a look on example: https://abf.io/build_lists/2476815
is papyros for armv7hl arch and it's ready to install just from official repo's.

**Comment by fedya** [comment] 2015-04-01 14:02
I'm pretty sure that papyros-shell never was in a working state ;)
And i still waiting for first working release.

**Closed** 2015-04-01 16:26 UTC

**Comment by ricardomv** [comment] 2015-04-01 16:37
@fedya i fixed the `iconSize` issue in the previous commit. If you have any more issues starting the shell please open a new issue but first check if there isn't one open yet. The glyph issue seems to be the same as reported in #38. The shell should work using qmlscene qml/main.qml in a X11 session, please also understand that QtCompositor is an experimental component and it's in active development so you can't expect it to work out of the box in every platform.

**Comment by fedya** [comment] 2015-04-01 20:20
Well, i rebuilt papyros-shell with your patch and now i got this

qrc:/qml/components/AppIcon.qml:98: ReferenceError: screenLocked is not defined
qrc:/qml/components/AppIcon.qml:174:16: Unable to assign [undefined] to QColor
qrc:/qml/components/AppIcon.qml:33: ReferenceError: application is not defined
qrc:/qml/components/AppIcon.qml:98: ReferenceError: screenLocked is not defined
qrc:/qml/components/AppIcon.qml:174:16: Unable to assign [undefined] to QColor
qrc:/qml/components/AppIcon.qml:33: ReferenceError: application is not defined
qrc:/qml/components/AppIcon.qml:98: ReferenceError: screenLocked is not defined
qrc:/qml/components/AppIcon.qml:174:16: Unable to assign [undefined] to QColor
qrc:/qml/components/AppIcon.qml:33: ReferenceError: application is not defined
qrc:/qml/components/AppIcon.qml:98: ReferenceError: screenLocked is not defined
qrc:/qml/components/AppIcon.qml:174:16: Unable to assign [undefined] to QColor
qrc:/qml/components/AppIcon.qml:33: ReferenceError: application is not defined
qrc:/qml/desktop/Workspace.qml:34: TypeError: Cannot call method 'indexOf' of undefined
qrc:/qml/desktop/Workspace.qml:34: TypeError: Cannot call method 'indexOf' of undefined
qrc:/qml/backend/UPower.qml:74: TypeError: Cannot read property 'percentage' of undefined
qrc:/qml/panel/Panel.qml:210: ReferenceError: screenLocked is not defined
qrc:/qml/lockscreen/Lockscreen.qml:51: TypeError: Cannot call method 'indexOf' of undefined

**Comment by iBeliever** [comment] 2015-04-01 21:15
@fedya Yes, Papyros has been in a working state in the past, and still works today in the `greenisland` branch. I've posted many screenshots of it working on our Google+ page. It's just very tricky to get working as it requires set up on the host computer along with compiling Qt 5.5 with the right configuration flags to enable QtCompositor to work.

@ricardomv Thanks for fixing the iconSize bug.

**Comment by fedya** [comment] 2015-04-01 23:22
@iBeliever looks like my issue related to imx6 board

**Comment by hsarkanen** [comment] 2015-04-02 11:37
@fedya Thanks for the info. If you have everything compiled in rootfs or rpm packages for Mandriva I would like to try it out on my imx6 board, you can contact my email in github account for example. Although I'm mostly interested running papyros-shell on my own Yocto distro not on Mandriva or Arch etc. Maybe it's not that interesting to try out any Qt version from 5.4 branch if 5.5 alpha1 is known to work without patches. I derived the patch from the one I spotted on [Freescale forum](https://community.freescale.com/message/450084#450084). There might be one other interesting [qtwayland version](https://github.com/maui-packages/qtwayland/tree/output54) to try out with the greenisland branch of papyros-shell. Good to know that kernel 3.19.2 works on imx6, I may try it also. I think we have the right Qt configure options like "wayland-compositor" enabled by default in the [Yocto toolchain](https://github.com/meta-qt5/meta-qt5/blob/master/recipes-qt/qt5/qtwayland.inc#L10). Also usable QtCompositor example might kind of prove that.

@iBeliever @ricardomv Thanks for the info and effort for creating a great Wayland based DE!

**Comment by fedya** [comment] 2015-04-02 12:14
@hsarkanen 
Options like WAYLAND-COMPOSITOR enabled in Oma by default
look: https://abf.io/openmandriva/qt5-qtwayland/blob/master/qt5-qtwayland.spec#lc-204

I'll send email to you with short instructions how to run oma on imx6
