### ISSUE TITLE
papyros-shell and eglfs

### ISSUE THREAD

**Issue by fedya** [papyros/papyros-shell#31] opened 2015-01-24 19:21 UTC
Hi i'm trying to run papyros-shell on I.MX6 based device (Sabre Board)
and i got this
[root@localhost ~]# DISPLAY=:0 papyros-shell -platform eglfs
libEGL warning: DRI2: xcb_connect failed
libEGL warning: DRI2: xcb_connect failed
Could not initialize egl display
Aborted (core dumped)

But i can run weston with such options
weston --tty=1 --backend=fbdev-backend.so
and it's working fine.
Might i can pass same option to papyros?

**Comment by iBeliever** [comment] 2015-03-06 15:35
This looks like a duplicate of #20.

**Closed** 2015-03-25 23:14 UTC
Labels: duplicate
