### ISSUE TITLE
hot corner overlaps window buttons

### ISSUE THREAD

**Issue by kingwill101** [papyros/papyros-shell#206] opened 2015-12-31 13:09 UTC
![screenshot_20151231_080655](https://cloud.githubusercontent.com/assets/1114368/12064606/88f33bd0-af95-11e5-9586-b9ee8425c0e2.png)

**Comment by alexkreidler** [comment] 2016-01-01 23:05
We really need to redesign and improve the hot corners.

**Comment by iBelieve** [comment] 2016-01-02 03:27
@Tim15 Indeed, see #130.

**Comment by iBelieve** [comment] 2016-01-02 03:28
I'm closing this as a duplicate of the above issue.

**Closed as completed by iBelieve** 2016-01-02 03:28 UTC
